### ISSUE TITLE
Can't use wp commands anymore

### ISSUE THREAD

**Issue by enoch85** [rhubarbgroup/redis-cache#253]
### Error

```
root@maintenance:/var/www/html/wordpress# sudo -u www-data /usr/local/bin/wp redis
PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/www/html/wordpress/wp-content/object-cache.php:539
Stack trace:
#0 /var/www/html/wordpress/wp-content/object-cache.php(411): WP_Object_Cache->connectUsingPhpRedis(Array)
#1 /var/www/html/wordpress/wp-content/object-cache.php(162): WP_Object_Cache->__construct(true)
#2 /var/www/html/wordpress/wp-includes/load.php(632): wp_cache_init()
#3 /var/www/html/wordpress/wp-settings.php(131): wp_start_object_cache()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('/var/www/html/w...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootst in /var/www/html/wordpress/wp-content/object-cache.php on line 539
Fatal error: Uncaught Error: Class 'Redis' not found in /var/www/html/wordpress/wp-content/object-cache.php:539
Stack trace:
#0 /var/www/html/wordpress/wp-content/object-cache.php(411): WP_Object_Cache->connectUsingPhpRedis(Array)
#1 /var/www/html/wordpress/wp-content/object-cache.php(162): WP_Object_Cache->__construct(true)
#2 /var/www/html/wordpress/wp-includes/load.php(632): wp_cache_init()
#3 /var/www/html/wordpress/wp-settings.php(131): wp_start_object_cache()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('/var/www/html/w...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootst in /var/www/html/wordpress/wp-content/object-cache.php on line 539
Error: There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.
```
### Config

```
Status: Connected
Client: PhpRedis (v5.3.1)
Drop-in: Valid
Disabled: No
Filesystem: Working
Ping: 1
Errors: []
PhpRedis: 5.3.1
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.2.24-0ubuntu0.18.04.6
Plugin Version: 2.0.11
Redis Version: 4.0.9
Multisite: No
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_CLIENT: "phpredis"
WP_REDIS_SCHEME: "unix"
WP_REDIS_PATH: "/var/run/redis/redis-server.sock"
WP_REDIS_MAXTTL: 9600
WP_REDIS_PREFIX: "maintenance_hanssonit_se_redis"
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "blog_meta"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes"
]
Unflushable Groups: []
Drop-ins: [
    "Redis Object Cache Drop-In v2.0.11 by Till Krüss"
]
```

Please let me know if you need more info.

Thanks for a great plugin!

**Comment by tillkruss** [comment]
Your CLI PHP runtime isn't loading the PhpRedis extension. You need to adjust your `php.ini` for you CLI runtime.

**Comment by enoch85** [comment]
@tillkruss 

> Your CLI PHP

This is PHP-FPM and it works in the fronted: https://cloud.hanssonit.se/s/YkmGnpPcjMae4S7

If I change to Predis it works in the backend as well.

**Comment by enoch85** [comment]
This is PHP-FPM, but it sure seems that adding it to both CLI and PHP-FPM did the tick.

Thanks!
