### ISSUE TITLE
Fatal Error in wp redis status

### ISSUE THREAD

**Issue by dhsathiya** [rhubarbgroup/redis-cache#265]
I am using AWS Elasticache in Non-cluster mode.

**What I am trying to achieve**
The aim is to set up this plugin in a way that read(GET) queries will get balanced between 2 instances and write queries go to the master (Primary) instance.

**AWS Setup**
Elasticache Redis.
1x Master (Primary) instance
1x Read-only instance

**wp-config.php**
```php
define( 'WP_REDIS_CLIENT', 'predis' );
define( 'WP_REDIS_SERVERS', [
    'tcp://example-com.rqcimx.ng.0001.aps1.cache.amazonaws.com:6379?alias=master',
    'tcp://example-com-ro.rqcimx.ng.0001.aps1.cache.amazonaws.com:6379?alias=replica-01',
] );
```
Note that I am using read-only & writer endpoint in above. I have also tried with a specific endpoint of the instance but the issue persists.

**Error**
No issues on WP settings page (https://example.com/wp-admin/options-general.php?page=redis-cache#diagnostics)

```
O_O[www-data@example.com:~/htdocs]$ wp redis status 
PHP Warning:  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/htdocs/current/wp-content/plugins/nginx-helper/includes/redis-delete.php on line 15
Warning: Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/htdocs/current/wp-content/plugins/nginx-helper/includes/redis-delete.php on line 15
PHP Fatal error:  Uncaught Error: Call to a member function test_filesystem_writing() on null in /var/www/htdocs/current/wp-content/plugins/redis-cache/includes/ui/diagnostics.php:13
Stack trace:
#0 /var/www/htdocs/current/wp-content/plugins/redis-cache/includes/cli/class-commands.php(36): require_once()
#1 [internal function]: Rhubarb\RedisCache\CLI\Commands->status(Array, Array)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command(Array, Array)
#7 phar:///usr/local/bin/wp/vendor/w in /var/www/htdocs/current/wp-content/plugins/redis-cache/includes/ui/diagnostics.php on line 13
Fatal error: Uncaught Error: Call to a member function test_filesystem_writing() on null in /var/www/htdocs/current/wp-content/plugins/redis-cache/includes/ui/diagnostics.php:13
Stack trace:
#0 /var/www/htdocs/current/wp-content/plugins/redis-cache/includes/cli/class-commands.php(36): require_once()
#1 [internal function]: Rhubarb\RedisCache\CLI\Commands->status(Array, Array)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command(Array, Array)
#7 phar:///usr/local/bin/wp/vendor/w in /var/www/htdocs/current/wp-content/plugins/redis-cache/includes/ui/diagnostics.php on line 13
Error: The site is experiencing technical difficulties.
```

**What I tried**
1. As the error was at function name including `filesystem` I have checked the file system for error related to permission.
    Also ran `chown -R www-data:www-data .` in site root.
2. Used Redis instance endpoints instead of read-only & writer endpoints but the same issue was there as well.

**Comment by tillkruss** [comment]
Thanks @dhsathiya, this was fixed in #266 and I'll tag a new version later today.
