### ISSUE TITLE
Uncaught Error: Call to a member function zrangebyscore()

### ISSUE THREAD

**Issue by thefrosty** [rhubarbgroup/redis-cache#291]
I got the following error when clicking "flush cache" from the settings page:

```
NOTICE: PHP message: [2020-10-14 15:12:45] PHP-ERROR.CRITICAL:
 Uncaught Error: Call to a member function zrangebyscore() on null in 
/usr/local/wordpress/wp-content/mu-plugins/redis-cache/includes/class-plugin.php:355 Stack trace: #0 /usr/local/wordpress/wp-includes/class-wp-hook.php(287): Rhubarb\RedisCache\Plugin->enqueue_redis_metrics('settings_page_r...') 
#1 /usr/local/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) 
#2 /usr/local/wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array) 
#3 /usr/local/wordpress/wp-admin/admin-header.php(102): do_action('admin_enqueue_s...', 'settings_page_r...') 
#4 /usr/local/wordpress/wp-admin/admin.php(239): require_once('/usr/local/word...') 
#5 /usr/local/wordpress/wp-admin/options-general.php(10): require_once('/usr/local/word...') 
#6 {main}   thrown {"file":"/usr/local/wordpress/wp-content/mu-plugins/redis-cache/includes/class-plugin.php","line":355} 
{"wp":{"doing_cron":false,"doing_ajax":false,"is_admin":true,"user_id":2}}
```

Diagnostic:
```
Status: Connected
Client: PhpRedis (v5.3.1)
Drop-in: Valid
Disabled: No
Filesystem: Failed to copy test file.
Ping: 1
Errors: []
PhpRedis: 5.3.1
Predis: Not loaded
Credis: Not loaded
PHP Version: 7.3.10
Plugin Version: 2.0.15
Redis Version: 5.0.0
Multisite: No
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_DISABLED: false
WP_REDIS_CLIENT: "pecl"
WP_REDIS_SCHEME: "tcp"
WP_REDIS_HOST: "REDACTED.amazonaws.com:6379"
WP_REDIS_CLUSTER: ["tcp://REDACTED.amazonaws.com:6379?database=0&alias=node-01","tcp://REDACTED.amazonaws.com:6379?database=0&alias=node-02"]
WP_REDIS_PREFIX: "REDACTED"
WP_CACHE_KEY_SALT: "REDACTED"
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "redis-cache",
    "blog_meta",
    "ludicrousdb"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes"
]
Unflushable Groups: []
Drop-ins: [
    "LudicrousDB (Error) v5.0.0 by JJJ & Friends",
    "LudicrousDB (Database) v5.0.0 by JJJ & Friends",
    "Redis Object Cache Drop-In v2.0.15 by Till Krüss"
]
```

**Comment by thefrosty** [comment]
![Kapture 2020-10-14 at 8 32 52](https://user-images.githubusercontent.com/367897/96011691-17f64c80-0df8-11eb-9a3d-bc42957f4336.gif)

**Comment by thefrosty** [comment]
![Kapture 2020-10-14 at 8 36 31](https://user-images.githubusercontent.com/367897/96011920-699ed700-0df8-11eb-9538-da7fdc382a10.gif)

**Comment by thefrosty** [comment]
Well, we only use Redis plugin as an mu-plugin. No other installs, and on docker deploy copy the object-cache.php file. 🤔

**Comment by tillkruss** [comment]
Try disabling all other plugins and see if that resolves the issue.

**Comment by thefrosty** [comment]
Will report back after. cc @martythornley

**Comment by tillkruss** [comment]
@thefrosty @martythornley any update on this?

**Comment by thefrosty** [comment]
Sorry I went on vacation for two weeks. After some testing we weren't able to solve the issue. We are currently rolling back to `v1.x`, and may be reaching out for further support in the coming weeks (for the PRO version).

**Comment by tillkruss** [comment]
@thefrosty Alright, thanks for the update. Hit me up anytime regarding Object Cache Pro ✌🏻
