### ISSUE TITLE
get_multiple() can cause an "Invalid argument supplied for foreach()" warning

### ISSUE THREAD

**Issue by ocean90** [rhubarbgroup/redis-cache#379]
I'm seeing a few warnings in our Sentry data where `$results` in https://github.com/rhubarbgroup/redis-cache/blob/afe483c4b0405fc997bd2bb89cf44350a40093b6/includes/object-cache.php#L1909 is not set, causing the "Warning: Invalid argument supplied for foreach()" PHP warning.
It seems like this happens when [the previous try/catch block](https://github.com/rhubarbgroup/redis-cache/blob/afe483c4b0405fc997bd2bb89cf44350a40093b6/includes/object-cache.php#L1885-L1902) catches an exception which sets `$cache` but not `$results`. ~Is it as simple as renaming the variable?~

I currently have no details about the exact exception which is thrown there but I'll follow-up on it once I have it.

<details>
<summary>Example stack backtraces</summary>

```
ErrorException: Warning: Invalid argument supplied for foreach()
#22 /home/vcap/app/web/content/object-cache.php(1904): WP_Object_Cache::get_multiple
#21 /home/vcap/app/web/content/object-cache.php(171): wp_cache_get_multiple
#20 /wp-includes/functions.php(6991): _get_non_cached_ids
#19 /wp-includes/taxonomy.php(3989): _prime_term_caches
#18 /wp-includes/taxonomy.php(3659): get_object_term_cache
#17 /wp-includes/post.php(7797): wp_queue_posts_for_term_meta_lazyload
#16 /wp-includes/class-wp-query.php(3344): WP_Query::get_posts
#15 /wp-includes/class-wp-query.php(3586): WP_Query::query
#14 /wp-includes/post.php(2410): get_posts
#13 /home/vcap/app/web/content/themes/theme/inc/template-functions.php(135): theme_add_feed_item_media
#12 /wp-includes/class-wp-hook.php(307): WP_Hook::apply_filters
#11 /wp-includes/class-wp-hook.php(331): WP_Hook::do_action
#10 /wp-includes/plugin.php(476): do_action
#9 /wp-includes/feed-rss2.php(125): require_once
#8 /wp-includes/template.php(770): load_template
#7 /wp-includes/functions.php(1662): do_feed_rss2
#6 /wp-includes/class-wp-hook.php(309): WP_Hook::apply_filters
#5 /wp-includes/class-wp-hook.php(331): WP_Hook::do_action
#4 /wp-includes/plugin.php(476): do_action
#3 /wp-includes/functions.php(1624): do_feed
#2 /wp-includes/template-loader.php(48): require_once
#1 /wp-blog-header.php(19): require
#0 /home/vcap/app/web/index.php(17): null


ErrorException: Warning: Invalid argument supplied for foreach()
#24 /home/vcap/app/web/content/object-cache.php(1904): WP_Object_Cache::get_multiple
#23 /home/vcap/app/web/content/object-cache.php(171): wp_cache_get_multiple
#22 /wp-includes/functions.php(6991): _get_non_cached_ids
#21 /wp-includes/taxonomy.php(3989): _prime_term_caches
#20 /wp-includes/taxonomy.php(3659): get_object_term_cache
#19 /home/vcap/app/web/content/plugins/polylang-pro/vendor/wpsyntex/polylang/include/translated-object.php(138): PLL_Translated_Object::get_object_term
#18 /home/vcap/app/web/content/plugins/polylang-pro/vendor/wpsyntex/polylang/include/translated-object.php(340): PLL_Translated_Object::get_translations
#17 /home/vcap/app/web/content/plugins/polylang-pro/modules/rest/rest-translated-object.php(130): PLL_REST_Translated_Object::get_translations
#16 /wp-includes/rest-api/endpoints/class-wp-rest-controller.php(433): WP_REST_Controller::add_additional_fields_to_object
#15 /wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php(857): WP_REST_Terms_Controller::prepare_item_for_response
#14 /wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php(290): WP_REST_Terms_Controller::get_items
#13 /wp-includes/rest-api/class-wp-rest-server.php(1143): WP_REST_Server::respond_to_request
#12 /wp-includes/rest-api/class-wp-rest-server.php(990): WP_REST_Server::dispatch
#11 /wp-includes/rest-api/class-wp-rest-server.php(700): WP_REST_Server::embed_links
#10 /wp-includes/rest-api/class-wp-rest-server.php(553): WP_REST_Server::response_to_data
#9 /wp-includes/rest-api/class-wp-rest-server.php(475): WP_REST_Server::serve_request
#8 /wp-includes/rest-api.php(394): rest_api_loaded
#7 /wp-includes/class-wp-hook.php(307): WP_Hook::apply_filters
#6 /wp-includes/class-wp-hook.php(331): WP_Hook::do_action
#5 /wp-includes/plugin.php(524): do_action_ref_array
#4 /wp-includes/class-wp.php(398): WP::parse_request
#3 /wp-includes/class-wp.php(770): WP::main
#2 /wp-includes/functions.php(1330): wp
#1 /wp-blog-header.php(16): require
#0 /home/vcap/app/web/index.php(17): null

ErrorException: Warning: Invalid argument supplied for foreach()
#15 /home/vcap/app/web/content/object-cache.php(1904): WP_Object_Cache::get_multiple
#14 /home/vcap/app/web/content/object-cache.php(171): wp_cache_get_multiple
#13 /wp-includes/taxonomy.php(3706): update_object_term_cache
#12 /home/vcap/app/web/content/plugins/polylang-pro/vendor/wpsyntex/polylang/include/translated-term.php(203): PLL_Translated_Term::_prime_terms_cache
#11 /wp-includes/class-wp-hook.php(309): WP_Hook::apply_filters
#10 /wp-includes/plugin.php(191): apply_filters
#9 /wp-includes/taxonomy.php(1334): get_terms
#8 /wp-includes/category.php(141): get_category_by_path
#7 /wp-includes/canonical.php(394): redirect_canonical
#6 /home/vcap/app/web/content/plugins/polylang-pro/vendor/wpsyntex/polylang/frontend/frontend-filters-links.php(454): PLL_Frontend_Filters_Links::check_canonical_url
#5 /wp-includes/class-wp-hook.php(307): WP_Hook::apply_filters
#4 /wp-includes/class-wp-hook.php(331): WP_Hook::do_action
#3 /wp-includes/plugin.php(476): do_action
#2 /wp-includes/template-loader.php(13): require_once
#1 /wp-blog-header.php(19): require
#0 /home/vcap/app/web/index.php(17): null

ErrorException: Warning: Invalid argument supplied for foreach()
#17 /home/vcap/app/web/content/object-cache.php(1904): WP_Object_Cache::get_multiple
#16 /home/vcap/app/web/content/object-cache.php(171): wp_cache_get_multiple
#15 /wp-includes/functions.php(6991): _get_non_cached_ids
#14 /wp-includes/taxonomy.php(3989): _prime_term_caches
#13 /wp-includes/taxonomy.php(3659): get_object_term_cache
#12 /wp-includes/post.php(7797): wp_queue_posts_for_term_meta_lazyload
#11 /wp-includes/class-wp-query.php(3344): WP_Query::get_posts
#10 /wp-includes/class-wp-query.php(3586): WP_Query::query
#9 /wp-includes/class-wp-query.php(3718): WP_Query::__construct
#8 /home/vcap/app/web/content/themes/theme/inc/template-tags.php(338): theme_one_two_posts
#7 /home/vcap/app/web/content/themes/theme/template-parts/content-home.php(47): require
#6 /wp-includes/template.php(772): load_template
#5 /wp-includes/template.php(716): locate_template
#4 /wp-includes/general-template.php(204): get_template_part
#3 /home/vcap/app/web/content/themes/theme/index.php(19): include
#2 /wp-includes/template-loader.php(106): require_once
#1 /wp-blog-header.php(19): require
#0 /home/vcap/app/web/index.php(17): null
```

</details>

**Comment by tillkruss** [comment]
This seems like a polylang issue. 

What exact parameters are being passed into `_get_non_cached_ids()`?

**Comment by ocean90** [comment]
Are you sure? The first and last backtrace doesn’t include any Polylang references. But I‘ll try to find out what the parameters are.

**Comment by tillkruss** [comment]
Mhhh, maybe the `array_combine()` is failing somehow:
https://github.com/rhubarbgroup/redis-cache/blob/afe483c4b0405fc997bd2bb89cf44350a40093b6/includes/object-cache.php#L1893-L1897

**Comment by ocean90** [comment]
Just noticed that Sentry already logs the parameters. The keys are looking legit to me, picked a few random entries:

```
force false
group terms
keys [
	2095
]


force false
group posts
keys [
	502679, 
	502634, 
	502619, 
	31918
]


force false
group terms
keys [
	35013
]

force false
group terms
keys [
	34947
]
```


Does https://github.com/rhubarbgroup/redis-cache/blob/afe483c4b0405fc997bd2bb89cf44350a40093b6/includes/object-cache.php#L1901 really make sense here? Isn't `$cache` filled by the loop for `$results` so we may need something like this instead?

```php
$results = array_combine(
    $remaining_keys,
    array_fill( 0, count( $remaining_ids ), false )
);
```

**Comment by tillkruss** [comment]
>really make sense here? Isn't $cache filled by the loop for $results so we may need something like this instead?

```php
$cache = array_fill( 0, count( $derived_keys ) - 1, false );
```

You're right, this could be better and only fill keys that weren't set via `get_from_internal_cache()`.

**Comment by tillkruss** [comment]
I think you might have to dump-and-die through this to see how `$results` is suddenly not an array.

**Comment by ocean90** [comment]
So far I'm not able to find the exact steps which are causing the warning. I kind of get part of it when both arrays don't have an equal number of elements but this will also generate a `Both parameters should have an equal number of elements` which I don't see in the logs.
This may happen if `mget()` for example returns less elements than requested.
https://github.com/rhubarbgroup/redis-cache/blob/c6e5eb1fc82ab45499a9c0706214a8ec20558136/includes/object-cache.php#L1893-L1894
But I don't think that will ever happen.


Anyway, in #383 I provided a PR for how I think `$results` should be set in case of an exception.

**Comment by tillkruss** [comment]
Excellent.
