### ISSUE TITLE
Memory leak in sitemap

### ISSUE THREAD

**Issue by altendorfme** [rhubarbgroup/redis-cache#416]
Specifically in a post type I get the following error when opening the sitemap:
```
[Mon Feb 06 14:59:15 2023] [PID:1507655 EID:Zuu2TU4nrCo] [php:error:sapi_apache2.c(353)] [Host:host.xyz Client:168.232.6.187:0] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 68438632 bytes) in /kunder/site/public/wp-content/object-cache.php on line 1243
[Mon Feb 06 14:59:15 2023] [PID:1507655 EID:Zuu2TU4nrCo] [php:error:sapi_apache2.c(353)] [Host:host.xyz Client:168.232.6.187:0] PHP Fatal error:  Uncaught Error: Trying to clone an uncloneable object of class Redis in /kunder/site/public/wp-content/object-cache.php:2565\nStack trace:\n#0 /kunder/site/public/wp-content/object-cache.php(1895): WP_Object_Cache->add_to_internal_cache()\n#1 /kunder/site/public/wp-content/object-cache.php(193): WP_Object_Cache->get()\n#2 /kunder/site/public/wp-content/plugins/wordpress-seo/src/repositories/indexable-repository.php(227): wp_cache_get()\n#3 /kunder/site/public/wp-content/plugins/wordpress-seo/src/repositories/indexable-repository.php(123): Yoast\\WP\\SEO\\Repositories\\Indexable_Repository->find_for_home_page()\n#4 /kunder/site/public/wp-content/plugins/wordpress-seo/src/memoizers/meta-tags-context-memoizer.php(97): Yoast\\WP\\SEO\\Repositories\\Indexable_Repository->for_current_page()\n#5 /kunder/site/public/wp-content/plugins/wordpress-seo/src/integrations/front-end/wp-robots-integration.php(87): Yoast\\WP\\SEO\\Memoizers\\Meta_Tags_Context_Memoizer->for_current_page()\n#6 /kunder/site/public/wp-content/plugins/wordpress-seo/src/integrations/front-end/wp-robots-integration.php(73): Yoast\\WP\\SEO\\Integrations\\Front_End\\WP_Robots_Integration->get_robots_value()\n#7 /kunder/site/public/wp-includes/class-wp-hook.php(308): Yoast\\WP\\SEO\\Integrations\\Front_End\\WP_Robots_Integration->add_robots()\n#8 /kunder/site/public/wp-includes/plugin.php(205): WP_Hook->apply_filters()\n#9 /kunder/site/public/wp-includes/robots-template.php(32): apply_filters()\n#10 /kunder/site/public/wp-includes/functions.php(3789): wp_robots()\n#11 /kunder/site/public/wp-content/plugins/advanced-access-manager/application/Service/DeniedRedirect.php(245): _default_wp_die_handler()\n#12 /kunder/site/public/wp-includes/functions.php(3713): AAM_Service_DeniedRedirect->processDie()\n#13 /kunder/site/public/wp-includes/class-wp-fatal-error-handler.php(239): wp_die()\n#14 /kunder/site/public/wp-includes/class-wp-fatal-error-handler.php(154): WP_Fatal_Error_Handler->display_default_error_template()\n#15 /kunder/site/public/wp-includes/class-wp-fatal-error-handler.php(58): WP_Fatal_Error_Handler->display_error_template()\n#16 [internal function]: WP_Fatal_Error_Handler->handle()\n#17 {main}\n  thrown in /kunder/site/public/wp-content/object-cache.php on line 2565
```

I tried limiting the Yoast sitemap to just 100 records and the error continued, only when I removed object-cache.php and disabled the plugin could I see the sitemap.

Only the first page of the sitemap does not open, the following ones open normally.

**Comment by tillkruss** [comment]
```
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 68438632 bytes) in /kunder/site/public/wp-content/object-cache.php on line 1243
PHP Fatal error:  Uncaught Error: Trying to clone an uncloneable object of class Redis in /kunder/site/public/wp-content/object-cache.php:2565\nStack trace:\n
#0 /kunder/site/public/wp-content/object-cache.php(1895): WP_Object_Cache->add_to_internal_cache()\n
#1 /kunder/site/public/wp-content/object-cache.php(193): WP_Object_Cache->get()\n
#2 /kunder/site/public/wp-content/plugins/wordpress-seo/src/repositories/indexable-repository.php(227): wp_cache_get()\n
#3 /kunder/site/public/wp-content/plugins/wordpress-seo/src/repositories/indexable-repository.php(123): Yoast\\WP\\SEO\\Repositories\\Indexable_Repository->find_for_home_page()\n
#4 /kunder/site/public/wp-content/plugins/wordpress-seo/src/memoizers/meta-tags-context-memoizer.php(97): Yoast\\WP\\SEO\\Repositories\\Indexable_Repository->for_current_page()\n
#5 /kunder/site/public/wp-content/plugins/wordpress-seo/src/integrations/front-end/wp-robots-integration.php(87): Yoast\\WP\\SEO\\Memoizers\\Meta_Tags_Context_Memoizer->for_current_page()\n
#6 /kunder/site/public/wp-content/plugins/wordpress-seo/src/integrations/front-end/wp-robots-integration.php(73): Yoast\\WP\\SEO\\Integrations\\Front_End\\WP_Robots_Integration->get_robots_value()\n
#7 /kunder/site/public/wp-includes/class-wp-hook.php(308): Yoast\\WP\\SEO\\Integrations\\Front_End\\WP_Robots_Integration->add_robots()\n
#8 /kunder/site/public/wp-includes/plugin.php(205): WP_Hook->apply_filters()\n
#9 /kunder/site/public/wp-includes/robots-template.php(32): apply_filters()\n
#10 /kunder/site/public/wp-includes/functions.php(3789): wp_robots()\n
#11 /kunder/site/public/wp-content/plugins/advanced-access-manager/application/Service/DeniedRedirect.php(245): _default_wp_die_handler()\n
#12 /kunder/site/public/wp-includes/functions.php(3713): AAM_Service_DeniedRedirect->processDie()\n
#13 /kunder/site/public/wp-includes/class-wp-fatal-error-handler.php(239): wp_die()\n
#14 /kunder/site/public/wp-includes/class-wp-fatal-error-handler.php(154): WP_Fatal_Error_Handler->display_default_error_template()\n
#15 /kunder/site/public/wp-includes/class-wp-fatal-error-handler.php(58): WP_Fatal_Error_Handler->display_error_template()\n#16 [internal function]: WP_Fatal_Error_Handler->handle()\n
#17 {main}\n  thrown in /kunder/site/public/wp-content/object-cache.php on line 2565
```

**Comment by tillkruss** [comment]
@A5hleyRich: Can you take a look at this one?

**Comment by tillkruss** [comment]
@A5hleyRich: I'd say use the WP Faker plugin to make a massive site and then run the sitemap generator if you can replicate it. If not, we need SSH access @altendorfme.

**Comment by tillkruss** [comment]
Just my email is fine 👍

**Comment by tillkruss** [comment]
@altendorfme: Is this still an issue?

**Comment by altendorfme** [comment]
@tillkruss I forwarded information to the server platform and it seems to have resolved it. ;)
