### ISSUE TITLE
RedisException: OOM command not allowed when used memory > 'maxmemory'

### ISSUE THREAD

**Issue by DrLightman** [rhubarbgroup/redis-cache#530]
Hi, just found this in Apache logs:

```
RedisException: OOM command not allowed when used memory > 'maxmemory'. in /opt/webroot/wp-content/object-cache.php:2212
Stack trace:
#0 /opt/webroot/wp-content/object-cache.php(2212): Redis->set()
#1 /opt/webroot/wp-content/object-cache.php(294): WP_Object_Cache->set()
#2 /opt/webroot/wp-includes/post.php(5747): wp_cache_set()
#3 /opt/webroot/wp-includes/class-wp.php(239): get_page_by_path()
#4 /opt/webroot/wp-includes/class-wp.php(780): WP->parse_request()
#5 /opt/webroot/wp-includes/functions.php(1332): WP->main()
#6 /opt/webroot/wp-blog-header.php(16): wp()
#7 /opt/webroot/index.php(17): require('/opt/webroot/...')
#8 {main}
```

## Steps to Reproduce
Unfortuntaly I have no clue.

## Environment
* Plugin version: 2.5.2
* PHP version: 7.4.13
* WordPress version: 6.1

**Comment by tillkruss** [comment]
Set a `maxmemory-policy`.
